tweak install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,32 +1,77 @@
 #!/bin/sh
 
+function error() {
+  echo -e "[ERROR] " $1
+  exit 1
+}
+
+function info() {
+  echo -e "[INFO] " $1
+}
+
+if [ ! `builtin command -v brew` ]; then
+  error 'Install homebrew before executing this install script.'
+fi
+
+# tpm
+if [ ! -e $HOME/.tmux/plugins/tpm ]; then
+  info 'Install tpm'
+  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+fi
+
+# brew
+info 'Install homebrew formulae'
+#brew install go tig fzf tmux starship zsh-autosuggestions gsed kubectl direnv htop fontconfig git-extras yarn
+#brew tap homebrew/cask-fonts
+#brew install --cask font-hack-nerd-font iterm2 vivaldi
+#brew install --HEAD neovim
+
+# Language server
+info 'Install Language servers'
+#yarn global add bash-language-server
+
 # zsh
+info 'Install .zshrc'
 if [ ! -h $HOME/.zshrc ]; then
     echo '=> ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc'
     ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc
+else
+  info '.zshrc is already installed' 
 fi
 
 # tmux 
+info 'Install .tmux.conf'
 if [ ! -h $HOME/.tmux.conf ]; then
     echo '=> ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf'
     ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf
+else
+  info '.tmux.conf is already installed' 
 fi
 
 # nvim
+info 'Install nvim configurations'
 if [ ! -h $HOME/.config/nvim ]; then
     echo '=> ln -sn $HOME/git/dotfiles/nvim $HOME/.config/nvim'
     ln -sn $HOME/git/dotfiles/nvim $HOME/.config/nvim
+else
+  info 'nvim configurations is already installed' 
 fi
 
 # tig
+info 'Install .tigrc'
 if [ ! -h $HOME/.tigrc ]; then
     echo '=> ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc'
     ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc
+else
+  info '.tigrc is already installed' 
 fi
 
-# gitcoinfg
-if [ ! -h $HOME/private/gitconfig ]; then
-    mkdir -p $HOME/private
-    echo '=> ln -sn $HOME/git/dotfiles/gitconfig $HOME/private/gitconfig'
-    ln -sn $HOME/git/dotfiles/gitconfig $HOME/private/gitconfig
+# private gitcoinfg
+info 'Install private git configuration'
+if [ ! -h $HOME/git/private/gitconfig ]; then
+    mkdir -p $HOME/git/private
+    echo '=> ln -sn $HOME/git/dotfiles/gitconfig $HOME/git/private/gitconfig'
+    ln -sn $HOME/git/dotfiles/gitconfig $HOME/git/private/gitconfig
+else
+  info '$HOME/git/private/gitconfig is already installed' 
 fi
